server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.128:1111 #集群中的nginx 代理到nacos
      #server-addr: localhost:8848 单机版的nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'
