server:
  port: 9527

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                           #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route        #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001             #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service         #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**               # 断言，路径相匹配的进行路由
            #- After=2021-02-04T08:32:32.400+08:00[Asia/Shanghai]

        - id: payment_routh2 #payment_route       #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001             #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service         #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**                 # 断言，路径相匹配的进行路由
            #- After=2021-02-04T08:32:32.400+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+             # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=www.tb.com
            #- Method=GET
            #- Query=username, \d+
          filters:
            #- AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id，值为：1024

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/